site_name: "Python DSA Notes"
site_url: https://yxshkm-notes.github.io/python-dsa-notes/
repo_url: https://github.com/yxshkm-notes/python-dsa-notes
repo_name: GitHub
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
nav:
  - Home: index.md
  - Basics:
      - Variables & Data Types: Basics/variables-and-types.md
      - Control Flow: Basics/control-flow.md
      - Loops: Basics/loops.md
      - Functions: Basics/functions.md
      - List Comprehensions: Basics/list-comprehensions.md
      - Error Handling: Basics/error-handling.md
      - Modules & Imports: Basics/modules-and-imports.md
  - Complexity Analysis:
      - "Big O, Big Θ, Big Ω": "Complexity Analysis/Big O, Big Θ, Big Ω.md"
      - Time & Space Complexity: "Complexity Analysis/Time & Space Complexity.md"
  - Algorithms:
      - Binary Search: Algorithms/binary-search.md
      - Bubble Sort: Algorithms/bubble-sort.md
      - Merge Sort: Algorithms/merge-sort.md
      - Quick Sort: Algorithms/quick-sort.md
      - BFS: Algorithms/bfs.md
      - DFS: Algorithms/dfs.md
      - Recursion: Algorithms/recursion.md
      - Dynamic Programming: Algorithms/dynamic-programming.md
  - Data Structures:
      - Lists: Data Structures/lists.md
      - Tuples: Data Structures/tuples.md
      - Sets: Data Structures/sets.md
      - Dictionaries: Data Structures/dictionaries.md
      - Stacks: Data Structures/stacks.md
      - Queues: Data Structures/queues.md
      - Linked Lists: Data Structures/linked-lists.md
      - Trees: Data Structures/trees.md
      - Heaps: Data Structures/heaps.md
      - Graphs: Data Structures/graphs.md
  - Practice:
      - Easy: Practice/Easy.md
      - Medium: Practice/Medium.md
      - Hard Arrays & Strings: Practice/hard_arrays_strings.md
      - Hard Trees & Graphs: Practice/hard_trees_graphs.md
      - Hard Linked List: Practice/hard_linked_lists.md
      - Hard Sorting & Searching: Practice/hard_sorting_searching.md
      - Hard Stacks & Queues: Practice/hard_stacks_queues.md
      
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - toc:
      permalink: true